grid_map_topic: /my_sdf_demo/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
      layer: elevation
  - name: sdf_points
    type: point_cloud
    params:
      layer: sdf
  - name: map_region
    type: map_region
    params:
      color: 3289650
      line_width: 0.05